<Project Sdk="Microsoft.NET.Sdk.Web">

  <ItemGroup>
    <ProjectReference Include="..\Clientes.Aplicacion\Clientes.Aplicacion.csproj" />
    <ProjectReference Include="..\Clientes.Infraestructura\Clientes.Infraestructura.csproj" />
    <ProjectReference Include="..\..\Construccion\Observabilidad.Compartida\Observabilidad.Compartida.csproj" />
  </ItemGroup>

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
  </PropertyGroup>

</Project>
