<Project Sdk="Microsoft.NET.Sdk">

  <ItemGroup>
    <ProjectReference Include="..\Clientes.Aplicacion\Clientes.Aplicacion.csproj" />
    <ProjectReference Include="..\Clientes.Dominio\Clientes.Dominio.csproj" />
    <ProjectReference Include="..\..\Construccion\Contratos.Compartidos\Contratos.Compartidos.csproj" />
  </ItemGroup>

  <ItemGroup>
    <FrameworkReference Include="Microsoft.AspNetCore.App" />
  </ItemGroup>

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

</Project>
